import {
    DEFAULTS_ALIGN,
    DEFAULTS_BLOCKQUOTE,
    DEFAULTS_BOLD,
    DEFAULTS_CODE,
    DEFAULTS_CODE_BLOCK,
    DEFAULTS_HEADING,
    DEFAULTS_HIGHLIGHT,
    DEFAULTS_IMAGE,
    DEFAULTS_ITALIC,
    DEFAULTS_KBD,
    DEFAULTS_LINK,
    DEFAULTS_LIST,
    DEFAULTS_MEDIA_EMBED,
    DEFAULTS_MENTION,
    DEFAULTS_PARAGRAPH,
    DEFAULTS_SEARCH_HIGHLIGHT,
    DEFAULTS_STRIKETHROUGH,
    DEFAULTS_SUBSUPSCRIPT,
    DEFAULTS_TABLE,
    DEFAULTS_TODO_LIST,
    DEFAULTS_UNDERLINE,
    ELEMENT_H1,
    ELEMENT_H2,
    ELEMENT_H3,
    ELEMENT_H4,
    ELEMENT_H5,
    ELEMENT_H6,
    setDefaults,
  } from '@udecode/slate-plugins';
  
  export const headingTypes = [
    ELEMENT_H1,
    ELEMENT_H2,
    ELEMENT_H3,
    ELEMENT_H4,
    ELEMENT_H5,
    ELEMENT_H6,
  ];
  
  export const options = {
    ...setDefaults(DEFAULTS_PARAGRAPH, {}),
    ...setDefaults(DEFAULTS_MENTION, {}),
    ...setDefaults(DEFAULTS_BLOCKQUOTE, {}),
    ...setDefaults(DEFAULTS_CODE_BLOCK, {}),
    ...setDefaults(DEFAULTS_LINK, {}),
    ...setDefaults(DEFAULTS_IMAGE, {}),
    ...setDefaults(DEFAULTS_MEDIA_EMBED, {}),
    ...setDefaults(DEFAULTS_TODO_LIST, {}),
    ...setDefaults(DEFAULTS_TABLE, {}),
    ...setDefaults(DEFAULTS_LIST, {}),
    ...setDefaults(DEFAULTS_HEADING, {}),
    ...setDefaults(DEFAULTS_ALIGN, {}),
    ...setDefaults(DEFAULTS_BOLD, {}),
    ...setDefaults(DEFAULTS_ITALIC, {}),
    ...setDefaults(DEFAULTS_UNDERLINE, {}),
    ...setDefaults(DEFAULTS_STRIKETHROUGH, {}),
    ...setDefaults(DEFAULTS_CODE, {}),
    ...setDefaults(DEFAULTS_KBD, {}),
    ...setDefaults(DEFAULTS_SUBSUPSCRIPT, {}),
    ...setDefaults(DEFAULTS_HIGHLIGHT, {}),
    ...setDefaults(DEFAULTS_SEARCH_HIGHLIGHT, {}),
  };