/**
 * This is the main entry point for distribution,
 * this file exposes the CMDEd components for external usage,
 * d.ts is autogenerated using tsc declaration = true
 * 
 * index.tsc is used for internal standalone execution.
 */
import CollabMarkdownEditor from "./Components/CollabMarkdownEditor";

export {
  CollabMarkdownEditor
};